config/routes.rb
Rails.application.routes.draw do
  
  resources :movies
  resources :series
  resources :documentary_films

  root "home#index"
  get 'documentary_films/index'
  post 'documentary_films/create'
  get 'documentary_films/new'
  get 'series/index' 
  post 'series/create'
  get 'series/new'
  get 'movies/index' 
  post 'movies/create'
  get 'movies/new'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/documentary_film.rb
class DocumentaryFilm < ApplicationRecord
    validates :name, :synopsis, :director, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
    validates :name, :synopsis, :director, presence: true
end

app/models/serie.rb
class Serie < ApplicationRecord
    validates :name, :synopsis, :director, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documentary_films_controller.rb
class DocumentaryFilmsController < ApplicationController
  def index
    @documentary_films = DocumentaryFilm.all
  end

  def create
    @documentary_film = DocumentaryFilm.new(documentary_film_params)
    if @documentary_film.save
      redirect_to documentary_films_path, notice: 'Documental creado exitosamente.'
    else
      render :new
    end
  end

  def new
    @documentary_film = DocumentaryFilm.new
  end

  def documentary_film_params
    params.require(:documentary_film).permit(:name, :synopsis, :director)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
       redirect_to movies_path, notice: 'Película creada exitosamente.'
    else
       render :new
    end
  end
  
  def new
    @movie = Movie.new
  end

  def movie_params
    params.require(:movie).permit(:name, :synopsis, :director)
  end

end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  def index
    @series = Serie.all
  end

  def create
    @serie = Serie.new(serie_params)
    if @serie.save
      redirect_to series_index_path, notice: 'Serie creada exitosamente.'
    else
      render :new
    end
  end
  
  def new
    @serie = Serie.new
  end

  def serie_params
    params.require(:serie).permit(:name, :synopsis, :director)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documentary_films_helper.rb
module DocumentaryFilmsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/documentary_films/create.html.erb
<!-- Vista de redirección, no es necesaria -->

app/views/documentary_films/index.html.erb
<main>
<div class="pricing-header p-3 pb-md-4 mx-auto text-center">
<h1 class="display-4 fw-normal text-body-emphasis">Documentary</h1>
<p class="fs-5 text-body-secondary">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sed enim veritatis sapiente, labore minus cum aperiam eum, eligendi ullam culpa laboriosam consequuntur! Asperiores alias aut fuga? Ullam hic quibusdam accusamus.</p>
</div>
<div class="row row-cols-1 row-cols-md-3 mb-5 text-center">
<table class="table">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Title</th>
      <th scope="col">Synopsis</th>
      <th scope="col">Director</th>
    </tr>
  </thead>
  <tbody>
  <% @documentary_films.each do |documentary_film| %>
    <tr>
    <th scope="row"><%= documentary_film.id %></th>
    <td><%= documentary_film.name %></td>
    <td><%= documentary_film.synopsis %></td>
    <td><%= documentary_film.director %></td>
  </tr>
<% end %>
  </tbody>
</table>
</div>

<div class="row row-cols-1 row-cols-md-3 mt-5 text-center justify-content-center">
<div class="col">
    <%= link_to 'Add Documentary', documentary_films_new_path, class: 'w-100 btn btn-lg btn-primary getbtn text-black border-0' %>
</div>
</div>
</main>

app/views/documentary_films/new.html.erb
<div class="pricing-header p-3 pb-md-4 mx-auto text-center">
<h1 class="display-4 fw-normal text-body-emphasis">Add Serie</h1>
<p class="fs-5 text-body-secondary">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sed enim veritatis sapiente, labore minus cum aperiam eum, eligendi ullam culpa laboriosam consequuntur! Asperiores alias aut fuga? Ullam hic quibusdam accusamus.</p>
</div>
<div class="row row-cols-1  mb-5 justify-content-center">
<div class="w-50">
<%= form_with model: @documentary_film, url: documentary_films_create_path do |form| %>
  <div class="mb-3">
    <label class="form-label">Documentary Title</label>
    <%= form.text_field :name, class:"form-control" %>
  </div>
  <div class="mb-3">
    <label class="form-label">Synopsis</label>
    <%= form.text_area :synopsis, class:"form-control" %>
  </div>
  <div class="mb-3">
  <label class="form-label">Director</label>
  <%= form.text_field :director, class:"form-control" %>
</div>
  <%= form.submit 'Save', class:"w-100 btn btn-lg btn-primary getbtn text-black border-0" %>
  <% end %>
  </div>
  </div>

app/views/home/index.html.erb
  <main>
  <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
  <h1 class="display-4 fw-normal text-body-emphasis">Welcome</h1>
  <p class="fs-5 text-body-secondary">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sed enim veritatis sapiente, labore minus cum aperiam eum, eligendi ullam culpa laboriosam consequuntur! Asperiores alias aut fuga? Ullam hic quibusdam accusamus.</p>
  </div>
    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
    <div class="col">
    <div class="card mb-4 movies rounded-3 shadow-sm">
      <div class="card-header py-3">
        <h4 class="my-0 fw-normal text-white">Movies</h4>
      </div>
      <div class="card-body">
        <ul class="list-unstyled mt-3 mb-4">
          <li class="py-5"></li>
        </ul>
        <%= link_to 'Get started', movies_path, class: "w-100 btn btn-lg btn-primary getbtn text-white border-0" %>
      </div>
    </div>
  </div>
      <div class="col">
        <div class="card mb-4 series rounded-3 shadow-sm">
          <div class="card-header py-3">
            <h4 class="my-0 fw-normal text-white">Series</h4>
          </div>
          <div class="card-body">
            <ul class="list-unstyled mt-3 mb-4">
              <li class="py-5"></li>
            </ul>
            <%= link_to 'Get started', series_index_path, class: "w-100 btn btn-lg btn-primary getbtn text-white border-0" %>
            </div>
        </div>
      </div>
      <div class="col">
      <div class="card mb-4 docu rounded-3 shadow-sm">
        <div class="card-header py-3">
          <h4 class="my-0 fw-normal text-white">Documentary</h4>
        </div>
        <div class="card-body">
          <ul class="list-unstyled mt-3 mb-4">
            <li class="py-5"></li>
          </ul>
          <%= link_to 'Get started', documentary_films_path, class: "w-100 btn btn-lg btn-primary getbtn text-white border-0" %>
          </div>
      </div>
    </div>
    </div>
  </main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Desafio3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="container py-3">
  <header>
    <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center link-body-emphasis text-decoration-none">
        <span class="fs-4">Marvalflix</span>
      </a>

      <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
        <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="/">Home</a>
        <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="/movies">Movies</a>
        <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="/series">Series</a>
        <a class="py-2 link-body-emphasis text-decoration-none" href="/documentary_films">Documentary</a>
      </nav>
    </div>
  </header>
    <%= yield %>
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
      <div class="col-12 col-md">
        <small class="d-block mb-3 text-body-secondary"><span>Marval</span> © 2023</small>
      </div>
      <div class="col-6 col-md">
      <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="/movies">Movies</a>
      </div>
      <div class="col-6 col-md">
      <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="/series">Series</a>
      </div>
      <div class="col-6 col-md">
      <a class="py-2 link-body-emphasis text-decoration-none" href="/documentary_films">Documentary</a>
      </div>
    </div>
  </footer>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>  </body>
</html>

app/views/movies/create.html.erb
<!-- Vista de redirección, no es necesaria -->

app/views/movies/index.html.erb
<main>
<div class="pricing-header p-3 pb-md-4 mx-auto text-center">
<h1 class="display-4 fw-normal text-body-emphasis">Movies</h1>
<p class="fs-5 text-body-secondary">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sed enim veritatis sapiente, labore minus cum aperiam eum, eligendi ullam culpa laboriosam consequuntur! Asperiores alias aut fuga? Ullam hic quibusdam accusamus.</p>
</div>
<div class="row row-cols-1 row-cols-md-3 mb-5 text-center">
<table class="table">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Title</th>
      <th scope="col">Synopsis</th>
      <th scope="col">Director</th>
    </tr>
  </thead>
  <tbody>
  <% @movies.each do |movie| %>
    <tr>
    <th scope="row"><%= movie.id %></th>
    <td><%= movie.name %></td>
    <td><%= movie.synopsis %></td>
    <td><%= movie.director %></td>
  </tr>
<% end %>
  </tbody>
</table>
</div>

<div class="row row-cols-1 row-cols-md-3 mt-5 text-center justify-content-center">
<div class="col">
    <%= link_to 'Add Movie', movies_new_path, class: 'w-100 btn btn-lg btn-primary getbtn text-black border-0' %>
</div>
</div>
</main>

app/views/movies/new.html.erb
<div class="pricing-header p-3 pb-md-4 mx-auto text-center">
<h1 class="display-4 fw-normal text-body-emphasis">Add Movie</h1>
<p class="fs-5 text-body-secondary">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sed enim veritatis sapiente, labore minus cum aperiam eum, eligendi ullam culpa laboriosam consequuntur! Asperiores alias aut fuga? Ullam hic quibusdam accusamus.</p>
</div>
<div class="row row-cols-1  mb-5 justify-content-center">
<div class="w-50">
<%= form_with(model: @movie, url: movies_create_path, local: true) do |form| %>
  <div class="mb-3">
    <label class="form-label">Movie Title</label>
    <%= form.text_field :name, class:"form-control" %>
  </div>
  <div class="mb-3">
    <label class="form-label">Synopsis</label>
    <%= form.text_area :synopsis, class:"form-control" %>
  </div>
  <div class="mb-3">
  <label class="form-label">Director</label>
  <%= form.text_field :director, class:"form-control" %>
</div>
  <%= form.submit 'Save', class:"w-100 btn btn-lg btn-primary getbtn text-black border-0" %>
  <% end %>
  </div>
  </div>

app/views/series/create.html.erb
<!-- Vista de redirección, no es necesaria -->

app/views/series/index.html.erb
<main>
<div class="pricing-header p-3 pb-md-4 mx-auto text-center">
<h1 class="display-4 fw-normal text-body-emphasis">Series</h1>
<p class="fs-5 text-body-secondary">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sed enim veritatis sapiente, labore minus cum aperiam eum, eligendi ullam culpa laboriosam consequuntur! Asperiores alias aut fuga? Ullam hic quibusdam accusamus.</p>
</div>
<div class="row row-cols-1 row-cols-md-3 mb-5 text-center">
<table class="table">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Title</th>
      <th scope="col">Synopsis</th>
      <th scope="col">Director</th>
    </tr>
  </thead>
  <tbody>
  <% @series.each do |serie| %>
    <tr>
    <th scope="row"><%= serie.id %></th>
    <td><%= serie.name %></td>
    <td><%= serie.synopsis %></td>
    <td><%= serie.director %></td>
  </tr>
<% end %>
  </tbody>
</table>
</div>

<div class="row row-cols-1 row-cols-md-3 mt-5 text-center justify-content-center">
<div class="col">
    <%= link_to 'Add Serie', series_new_path, class: 'w-100 btn btn-lg btn-primary getbtn text-black border-0' %>
</div>
</div>
</main>

app/views/series/new.html.erb
<div class="pricing-header p-3 pb-md-4 mx-auto text-center">
<h1 class="display-4 fw-normal text-body-emphasis">Add Serie</h1>
<p class="fs-5 text-body-secondary">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sed enim veritatis sapiente, labore minus cum aperiam eum, eligendi ullam culpa laboriosam consequuntur! Asperiores alias aut fuga? Ullam hic quibusdam accusamus.</p>
</div>
<div class="row row-cols-1  mb-5 justify-content-center">
<div class="w-50">
<%= form_with model: @serie, url: series_create_path do |form| %>
    <div class="mb-3">
    <label class="form-label">Serie Title</label>
    <%= form.text_field :name, class:"form-control" %>
  </div>
  <div class="mb-3">
    <label class="form-label">Synopsis</label>
    <%= form.text_area :synopsis, class:"form-control" %>
  </div>
  <div class="mb-3">
  <label class="form-label">Director</label>
  <%= form.text_field :director, class:"form-control" %>
</div>
  <%= form.submit 'Save', class:"w-100 btn btn-lg btn-primary getbtn text-black border-0" %>
  <% end %>
  </div>
  </div>